### ISSUE TITLE
Tiles get offset after adding an openWebsite layer

### ISSUE THREAD

**Issue by naugess** [thecodingmachine/workadventure-map-starter-kit#3]
Hi! I tried to add an openWebsite layer, and while that function kind of works, it appears to have messed up the way it's interpreting the tilesets. This happened last time I did it too (I just recloned), and I didn't touch anything about the tilesets. You can see the results at https://play.workadventu.re/_/global/naugess.github.io/Convention/map.json and the very-little-changed code at https://github.com/naugess/Convention/tree/gh-pages. 

Can you help me avoid this mess?

**Comment by moufmouf** [comment]
Hi @naugess ,

Interesting. This is probably linked to tiles being "extruded" (see https://github.com/sporadic-labs/tile-extruder)
Basically, when you commit on the "master" branch, Github Action is running. It is a process that will modify your tileset to "extrude" it. Extruding the tileset means adding a 1 pixel around each tile. We need to do this because of rounding errors in WebGL that cause graphical glitches.

The 'extruded' tileset is then commited in the gh-pages branch.

I'm not 100% sure but it looks like you are using a tileset that is already extruded and that the tileset gets extruded twice.

Are you working/commiting on the master branch?
Are the tiles in your PNG files measuring 32x32 pixels (as they should) or are they measuring 34x34 pixels?

**Comment by naugess** [comment]
I'd been committing in both master and gh-pages, as gh-pages didn't look like it was updating when I committed to master. Should I be committing only in one or the other?

Both tilesets look like 32x32 in the version I've been updating... but I've only been uploading the changed json. Should I be reuploading tilesets too?

**Comment by moufmouf** [comment]
I think you should only commit to master.
You should not take the JSON from ghpages and commit it back to master.

When you commit to master, Github Action will be triggered. It can take a few minutes to complete, so you will not see the changes right away.

**Comment by naugess** [comment]
Thank you!

**Comment by deroguerre** [comment]
Hello moufmouf, I started using your project for my compagny today, so I follow the documentation to deploy the starting kit on github and start editing my map with tiled, but I see that "floortileset.png" and "tilesets_deviant_milkian_1.png" are already extruded in branch gh-pages, it's normal ?

**Comment by ValdoTR** [comment]
I close this issue as it seems to be resolved.
